-- MySQL Script generated by MySQL Workbench
-- mar 01 ago 2023 15:28:53
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema PROYECTO_ASISTENCIA
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `PROYECTO_ASISTENCIA` ;

-- -----------------------------------------------------
-- Schema PROYECTO_ASISTENCIA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PROYECTO_ASISTENCIA` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `PROYECTO_ASISTENCIA` ;

-- -----------------------------------------------------
-- Table `PROYECTO_ASISTENCIA`.`Alumno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PROYECTO_ASISTENCIA`.`Alumno` ;

CREATE TABLE IF NOT EXISTS `PROYECTO_ASISTENCIA`.`Alumno` (
  `idAlumno` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `foto` BLOB NOT NULL,
  PRIMARY KEY (`idAlumno`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `PROYECTO_ASISTENCIA`.`Materia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PROYECTO_ASISTENCIA`.`Materia` ;

CREATE TABLE IF NOT EXISTS `PROYECTO_ASISTENCIA`.`Materia` (
  `idMateria` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMateria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `PROYECTO_ASISTENCIA`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PROYECTO_ASISTENCIA`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `PROYECTO_ASISTENCIA`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `admin` TINYINT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `user` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `PROYECTO_ASISTENCIA`.`Curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PROYECTO_ASISTENCIA`.`Curso` ;

CREATE TABLE IF NOT EXISTS `PROYECTO_ASISTENCIA`.`Curso` (
  `idCurso` INT NOT NULL,
  `idMateria` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  `horario` VARCHAR(45) NOT NULL,
  `dias` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCurso`),
  INDEX `fk_materia_idx` (`idMateria` ASC) VISIBLE,
  INDEX `fk_usuario_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_materia`
    FOREIGN KEY (`idMateria`)
    REFERENCES `PROYECTO_ASISTENCIA`.`Materia` (`idMateria`),
  CONSTRAINT `fk_usuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `PROYECTO_ASISTENCIA`.`Usuario` (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `PROYECTO_ASISTENCIA`.`Agenda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PROYECTO_ASISTENCIA`.`Agenda` ;

CREATE TABLE IF NOT EXISTS `PROYECTO_ASISTENCIA`.`Agenda` (
  `idAgenda` INT NOT NULL,
  `idAlumno` INT NOT NULL,
  `idCurso` INT NOT NULL,
  PRIMARY KEY (`idAgenda`),
  INDEX `fk_alumno_idx` (`idAlumno` ASC) VISIBLE,
  INDEX `fk_curso_idx` (`idCurso` ASC) VISIBLE,
  CONSTRAINT `fk_alumno`
    FOREIGN KEY (`idAlumno`)
    REFERENCES `PROYECTO_ASISTENCIA`.`Alumno` (`idAlumno`),
  CONSTRAINT `fk_curso`
    FOREIGN KEY (`idCurso`)
    REFERENCES `PROYECTO_ASISTENCIA`.`Curso` (`idCurso`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `PROYECTO_ASISTENCIA`.`Clase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PROYECTO_ASISTENCIA`.`Clase` ;

CREATE TABLE IF NOT EXISTS `PROYECTO_ASISTENCIA`.`Clase` (
  `idClase` INT NOT NULL,
  `idCurso` INT NOT NULL,
  `fecha` VARCHAR(45) NOT NULL,
  `horaInicio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idClase`),
  INDEX `fk_clase_idx` (`idCurso` ASC) VISIBLE,
  CONSTRAINT `fk_clase`
    FOREIGN KEY (`idCurso`)
    REFERENCES `PROYECTO_ASISTENCIA`.`Curso` (`idCurso`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `PROYECTO_ASISTENCIA`.`Asistencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PROYECTO_ASISTENCIA`.`Asistencia` ;

CREATE TABLE IF NOT EXISTS `PROYECTO_ASISTENCIA`.`Asistencia` (
  `idAsistencia` INT NOT NULL,
  `idAlumno` INT NOT NULL,
  `idClase` INT NOT NULL,
  `status` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`idAsistencia`),
  INDEX `fk_alumno_idx` (`idAlumno` ASC) VISIBLE,
  INDEX `fk_clase_idx` (`idClase` ASC) VISIBLE,
  CONSTRAINT `fk_Asistencia_1`
    FOREIGN KEY (`idAlumno`)
    REFERENCES `PROYECTO_ASISTENCIA`.`Alumno` (`idAlumno`),
  CONSTRAINT `fk_Asistencia_2`
    FOREIGN KEY (`idClase`)
    REFERENCES `PROYECTO_ASISTENCIA`.`Clase` (`idClase`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `PROYECTO_ASISTENCIA`.`Sesion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PROYECTO_ASISTENCIA`.`Sesion` ;

CREATE TABLE IF NOT EXISTS `PROYECTO_ASISTENCIA`.`Sesion` (
  `idSesion` INT NOT NULL,
  `dia` VARCHAR(1) NOT NULL,
  `hora_inicio` INT NOT NULL,
  `hora_fin` INT NOT NULL,
  PRIMARY KEY (`idSesion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `PROYECTO_ASISTENCIA`.`Horario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PROYECTO_ASISTENCIA`.`Horario` ;

CREATE TABLE IF NOT EXISTS `PROYECTO_ASISTENCIA`.`Horario` (
  `idHorario` INT NOT NULL,
  `idCurso` INT NOT NULL,
  `idSesion` INT NOT NULL,
  PRIMARY KEY (`idHorario`),
  INDEX `fk_Horario_1_idx` (`idSesion` ASC) VISIBLE,
  INDEX `fk_Horario_2_idx` (`idCurso` ASC) VISIBLE,
  CONSTRAINT `fk_Horario_1`
    FOREIGN KEY (`idSesion`)
    REFERENCES `PROYECTO_ASISTENCIA`.`Sesion` (`idSesion`),
  CONSTRAINT `fk_Horario_2`
    FOREIGN KEY (`idCurso`)
    REFERENCES `PROYECTO_ASISTENCIA`.`Curso` (`idCurso`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
